## SealedSecret
- name: "Verify that required string variables are defined"
  assert:
    that: 
      - required_variable is defined
      - required_variable | length > 0
      - required_variable != None
    fail_msg: "{{ required_variable }} needs to be set for the role to work"
    success_msg: "Required variable {{ required_variable}} is defined"
  loop_control:
    loop_var: required_variable
  with_items:
    - "{{ SEALED_SECRET_RELEASE }}"
    - "{{ SEALED_SECRET_KEY }}"
    - "{{ SEALED_SECRET_CERTIFICATE }}"
  no_log: True

- name: Create secret for sealed secret
  shell: echo "{{ lookup('template', 'sealed-secrets-key.j2') }}" | kubectl apply -f -
  register: result

- debug:
    var: result.stdout

- name: Download Controller manifest
  shell: wget https://github.com/bitnami-labs/sealed-secrets/releases/download/{{ SEALED_SECRET_RELEASE }}/controller.yaml
  register: result

- name: Download Controller manifest
  replace:
    path: controller.yaml
    regexp: 'quay.io/bitnami/sealed-secrets-controller'
    replace: "bitnami/sealed-secrets-controller"

- name: Create controller for sealed secrets
  shell: kubectl apply -f controller.yaml
  register: result

- name: Delete controller yaml
  file:
    state: absent
    path: controller.yaml


- debug:
    var: result.stdout